### ISSUE TITLE
Header Values to Zero?

### ISSUE THREAD

**Issue by abellgithub** [ASPRSorg/LAS#101]
Section 2.4 of the current specification says:

"Note: Any field in the Public Header Block that is not required and is not used must be zero filled."

It is not clear to me what that means. In which instances is a field "not required"?

I am currently interested in the case where the file contains no points, though some general clarification seems in order, or perhaps the statement should be struck.

**Comment by esilvia** [comment]
One simple scenario can occur when the System Identifier or Project ID fields are left blank. In this case all relevant bytes should be set to zero.

I've also seen use cases where the System Identifier is null-terminated but the LAS header left garbage in the remaining unused characters. For example, "Sensor 1234" only requires 12 characters if null-terminated. The remaining 20 characters should also be set to null for the header to be valid.

For your particular use case of zero points, the point statistics (Min/Max XYZ, point counts, return tallies, legacy point counts) should be set to null as they are "not required" for describing nonexistent points.

**Comment by rapidlasso** [comment]
Why is the USGS defaming, slandering and abusing me? These are totally false allegations!!!
![HIGH_PRIORITY_LASTool_Suite_Presents_Potential_Risk_to_USGS_Projects_and_Programs](https://user-images.githubusercontent.com/1107656/104672986-1aab5b00-56e1-11eb-8d36-1702c7e42919.png)
