### ISSUE TITLE
Miscalculation of the GUID representations example?

### ISSUE THREAD

**Issue by kkk669** [ASPRSorg/LAS#111]
On [this page](https://github.com/ASPRSorg/LAS/wiki/LAS-ProjectID-Encoding-and-Representation#guiduuid-representations), it shows that the first part of `00112233-4455-6677-8899-AABBCCDDEEFF` is represented as `33 22 11 00` in raw hex and as `1122867` (=`0x00112233`) in integer.

However, I think it must be `857870592` (=`0x33221100`). Because the second and third parts are represented as `21828` (=`0x5544`) and `30566` (=`0x7766`) in integer on the page, unlike the first part, though it explains that the first three parts are all encoded in Little-Endian.

If I'm wrong, please close this issue. Thanks.

**Comment by esilvia** [comment]
Thanks for bringing this up! You're right that I mixed up the endianness of the integer interpretation, but in the other direction. It's the integer values of the middle bytes that I messed up.

Because of LittleEndian interpretation, the following should be true:

```
Raw Hex         Hex (translated)   Integer (LE)
[33 22 11 00]   [0x00112233]       ui32=1122867
[55 44]         [0x4455]           ui16=17493
[77 66]         [0x6677]           ui16=26231
```

I've attached a binary GUID encoded as described in hopes that'll clarify. Note that it's not actually a txt file... I just had to give it that suffix for GitHub to allow the upload. 

[guid.txt](https://github.com/ASPRSorg/LAS/files/6826643/guid.txt)

I'll update the wiki shortly.

**Comment by esilvia** [comment]
It seems that I made the same mistake in the other example. Thanks for bringing this to my attention. I'll upload sample GUIDs for both.

**Comment by esilvia** [comment]
The wiki has been updated and now also includes LAS and bin samples.

https://github.com/ASPRSorg/LAS/wiki/LAS-ProjectID-Encoding-and-Representation

@kkk669 Would you mind double-checking my examples?

**Comment by kkk669** [comment]
Thank you so much. Your changes look good to me.

- https://github.com/ASPRSorg/LAS/wiki/LAS-ProjectID-Encoding-and-Representation/_compare/2f1697ca042ad15ca630ea0637f0a6b5f3d8bf00...99685c6f189eeba42d02db1fdf23d7c9d1624fee
- https://github.com/ASPRSorg/LAS/wiki/LAS-ProjectID-Encoding-and-Representation/_compare/99685c6f189eeba42d02db1fdf23d7c9d1624fee...e10707dc4574796a94db5a11e290442365a53979
- https://github.com/ASPRSorg/LAS/wiki/LAS-ProjectID-Encoding-and-Representation/_compare/e10707dc4574796a94db5a11e290442365a53979...d4a9a05863e230849473bf7454d508e868a86913

If I had to say, the word "integers" in the following line can be a little confusing.

```
LAS Project ID (integers):     [1122867    ][17493][26231][136 153 170 187 204 221 238 255]
```

How about this?

```
LAS Project ID (integers):     [1122867    ][17493][26231][136 153 170 187 204 221 238 255] <-- note the first three sections are interpreted as LE
```

**Comment by esilvia** [comment]
Done! Sorry for the delay.
