### ISSUE TITLE
Correctness of data type definitions

### ISSUE THREAD

**Issue by plimkilde** [ASPRSorg/LAS#115]
The spec currently refers to the C99 standard for the definition of the data types used (`char`, `short`, `long` etc.). As far as I can tell, taking this at face value may be self-contradictory and not reflect how LAS data should actually be parsed.

The "classic" C integer data types are permitted to have any of three different representations for signed integers (sign-and-magnitude, two's complement, one's complement) and, rather than having exact specified widths, merely have minimum requirements for the ranges they can hold (e.g. [-2147483647, +2147483647] for `long`). This could be a real problem since `long` is commonly 64 bits wide these days.

I suppose the desired behavior is actually that of C99's exact-width types, which are also guaranteed to be two's complement for the signed types. Thus, the integer types should be handled like this:

Type name in LAS spec | Intended C99 type (stdint.h)
--- | ---
`char` | `int8_t`
`unsigned char` | `uint8_t`
`short` | `int16_t`
`unsigned short` | `uint16_t`
`long` | `int32_t`
`unsigned long` | `uint32_t`
`long long` | `int64_t`
`unsigned long long` | `uint64_t`

Note also that `char` in C may be either of `signed char` and `unsigned char`.

The `float` and `double` may technically not map to the single/double types in IEEE 754/IEC 60559. However, the C99 spec has extensive provisions for the common case when they do (they should map properly if `__STDC_IEC_559__` is defined) as described in Annex F. Thus, it should suffice with a remark that these two types are 32- and 64-bit IEEE types, respectively (as is currently the case).

I'm not sure how all this should be addressed in the spec, but directly referring to C99's definitions for the integer type names seems incorrect.

**Comment by esilvia** [comment]
@plimkilde I just refreshed the example PDF with your proposed change that can be downloaded here for the next 30 days:
https://github.com/ASPRSorg/LAS/suites/5525142074/artifacts/177388595

Can you take a look and let me know if that addresses your concern? If not, I'll just close this ticket as inactive.

**Comment by plimkilde** [comment]
Sorry about the long wait, I finally got around to making a PR now.

**Comment by esilvia** [comment]
Here's a PDF version with all changes incorporated, plus adjustments of column widths to account for the more compact format. 

[LAS_#115.pdf](https://github.com/ASPRSorg/LAS/files/8308273/LAS_.115.pdf)

I did a quick read-through and fixed the one missing reference I saw. 

There's a few references to `UINT32_MAX` and similar. Should those also be adjusted?

**Comment by plimkilde** [comment]
Thanks! I don't know how the `ushort` reference slipped through, but great that it's caught.

The `UINT32_MAX` macro is defined in C99 as the upper limit of the `uint32_t` type, so that should be all good.

**Comment by esilvia** [comment]
Sounds good, thanks! This is now queued for inclusion in R16. Thanks for the contribution @plimkilde !
