### ISSUE TITLE
Standard System Identifiers downloads contain incorrect informat

### ISSUE THREAD

**Issue by rsking** [ASPRSorg/LAS#123]
The information in the CSV and XLSX files are incorrect when compared to the wiki

In the CSV, the `Livox` and `Hesai Technology` have the same codes. The `Hesai Technology` are just a copy of the `Livox` ones.

In the XLSX, the `Livox` and `Hesai Technology` codes are around the wrong way.

Attached are files that are correct
[models.csv](https://github.com/ASPRSorg/LAS/files/8829007/models.csv)
[System_ID_codes_master.xlsx](https://github.com/ASPRSorg/LAS/files/8829008/System_ID_codes_master.xlsx)

**Comment by esilvia** [comment]
Great catch! Those have now been corrected on the wiki.
