### ISSUE TITLE
Reserve LASF_Projection:4224 for 1.5 WKT2

### ISSUE THREAD

**Issue by hobu** [ASPRSorg/LAS#126]
### What is the issue about?

Inquiry about the specification, Other

### Issue description

The PDAL community [intends to](https://github.com/PDAL/PDAL/pull/3998) start using `LASF_Projection:4224` to insert WKTv2 content into LAS files. While we could be using `PDAL:4224` to do this (like we did way back in the day with `libLAS:2112`), the intention is that LAS 1.5 is going to provide WKTv2 support, and it would make sense to declare which record ID the specification would use.

Additionally, we would also plan to start using `PDAL:4225` to insert [PROJJSON](https://proj.org/specifications/projjson.html) VLRs. PROJJSON is a faithful alternative encoding of WKTv2 that is more convenient and does not require a custom parser for syntax validation (it uses [json-schema](https://json-schema.org/)). The committee might consider making a statement about using PROJJSON too, although which to prefer when is likely to get confusing.

**Comment by esilvia** [comment]
Weird... I thought I left a comment when I edited the tags last month, but apparently it didn't stick. Sorry about that. If you want to pre-emptively reserve that code for LAS 1.5 in LASF_Projection I think that's fine. We just need to include that in the LAS 1.5 spec.

**Comment by esilvia** [comment]
In today's conf call we decided that a new VLR will not be needed for WKTv2, except for the one described in #129
