### ISSUE TITLE
Fully deprecate PDRFs 0-5 for LAS 1.5

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#128]
### What is the issue about?

Inquiry about the specification

### Issue description

LAS 1.4 discouraged but allowed use of PDRFs 0-5 as long as WKT CRS isn't present.

Should LAS 1.5 prohibit their use altogether? If we do, then by definition that means that Geotiff codes will also be prohibited.

**Comment by esilvia** [comment]
Notes for text:

1. We will NOT change the meaning of existing PDRF codes (i.e., PDRF 6 won't become PDRF 1). People will probably create LAS 1.5 files with PDRF1, for example, but it's not a valid LAS and a reader doesn't have to support it.
2. Explicitly prohibit use of Geotiff VLRs. Again, people will do it, but that doesn't mean that it's valid.
3. Definitions of PDRFs 0-5 will be REMOVED entirely, with a small note about their deprecation as of LAS 1.5.
4. Update Global Encoding bit language to reflect Geotiff code removal.
5. Remove Geotiff VLR definitions. Move to [wiki of known VLRs](https://github.com/ASPRSorg/LAS/wiki/User-Contributed-VLRs)?

**Comment by esilvia** [comment]
Worked on today during Oct 2023 LWG meeting. Completed moving PDRF attribute descriptions from 0-5 to 6-10, except Classification and Scan Angle Rank. Still need to finish those two and remove PDRFs 0-5. Introductory paragraphs should also be updated.
![image](https://github.com/ASPRSorg/LAS/assets/11743012/202a6776-c41e-4613-944c-d3a73b05e02c)

**Comment by hobu** [comment]
> Completed moving PDRF attribute descriptions from 0-5 to 6-10, 

What does this mean, exactly? I understood our "full deprecation" of PDRFs 0-5 to mean they were no longer valid, but we were not going to change any PDRF numbers. Is that still the case?

**Comment by kjwaters** [comment]
Howard,
Yes, no change in the PDRF numbers.

Kirk

**Comment by esilvia** [comment]
That's correct. I intend to remove the descriptions of PDRFs 0-5 and label them as deprecated in the LAS 1.5 specification. However, several attributes (like XYZ) only had descriptions in the PDRF0 definition and so those attribute descriptions needed to be moved to the PDRF6+ definition.

Does that make sense? Does this plan sound good, or were you thinking that we would leave in the PDRF0-5 descriptions?

**Comment by hobu** [comment]
> Does this plan sound good, or were you thinking that we would leave in the PDRF0-5 descriptions?

Maybe a note that states these PDRFs were defined by older versions of the specification and were removed for 1.5. 

Maybe we should explicitly state that any 1.5 file with PDRF 0-5 in them is INVALID.

**Comment by manfred-brands** [comment]
As auser, assuming semantic versioning, removing support for older PDRFs would require you to call this version 2.

**Comment by hobu** [comment]
If LAS had semantic versioning we would be at version 6 or 7 at this point 😉 

I don't think we've made any such promises.

**Comment by esilvia** [comment]
Issue branch has been merged into `draft-1.5` branch. I forgot to tag the commit, sorry.
