### ISSUE TITLE
Ambiguity of Creation Day of Year and Creation Year

### ISSUE THREAD

**Issue by hobu** [ASPRSorg/LAS#138]
### What is the issue about?

Inquiry about the specification

### Issue description

I am wondering if there is an ambiguity in the language of these two header items. I have always taken "the file was created" to mean "when the point data stored in this LAS file were captured", not "when this file was written to disk". 

Which is it?

### File Creation Day of Year

> Day, expressed as a uint16_t, on which this file was created. Day is computed as the Greenwich Mean Time (GMT) day. January 1 is considered day 1.

### File Creation Year

> The year, expressed as a four digit number, in which the file was created.

**Comment by esilvia** [comment]
I agree with Kirk on all points, although I have seen it used both ways. I agree that the current writing leaves room for interpretation.

**Comment by hobu** [comment]
> I've also usually found these header fields of little or no use.

Me too, other than using them to calculate which GPSWeek.

**Comment by kjwaters** [comment]
Connor,
I think that is aligned with initial reasoning for the field, assuming
you're working with swath data. The data with GPS seconds of the week is
(hopefully) older data. In my experience it is rarely found in swath format
and even when it is, this field is often not filled out such that you can
figure out the week. That's why I don't usually find it useful.

Kirk

**Comment by mgswartz1** [comment]
Suggestion:  If GPS Week Time is used, The GPS Week should be included in a VLR or EVLR.

**Comment by esilvia** [comment]
I have always liked the idea of a lookup table VLR that matched PtSourceID with GPS Weeks. Having a single value for an entire file does not work because of prolonged large scale collections spanning many weeks/months/years.

**Comment by abellgithub** [comment]
One could clarify that the day/year should be the date the file was produced.

One could also take a few bits from global encoding to specify the GPS week range. I'm sure 4 bits would do or would get us by until we're all dead.
