### ISSUE TITLE
Clarification about File Creation Day of Year

### ISSUE THREAD

**Issue by wiesehahn** [ASPRSorg/LAS#148]
### What is the issue about?

Inquiry about the specification

### Issue description

In the specification under 2.4 it says 

> File Creation Day of Year
Day, expressed as an unsigned short, on which this file was created. Day is computed as the Greenwich Mean Time (GMT) day. January 1 is considered day 1.

Does this actually has nothing to do with data aquisition but means the date when the file was created (e.g. after initial processing)?

**Comment by Jean-Romain** [comment]
See also this discussion https://github.com/ASPRSorg/LAS/issues/138 where the question has already been asked

**Comment by wiesehahn** [comment]
thought I had a look if there was an issue already, sorry. 
Still confusing to me anyway.
