### ISSUE TITLE
Improve readability of tables

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#15]
Howard's port from Word didn't include bold text in the headers of the tables. Fix that to make tables more readable. Also, ensure that line breaks occur properly and that tables break across pages.

**Comment by esilvia** [comment]
Figured it out. Applying a global setting was a matter of adding `\protected\def\sphinxstylethead{\textbf}` to the `preamble` in [conf.py](https://github.com/ASPRSorg/LAS/blob/master/source/conf.py).

Sphinx wraps the contents of the header row in `\spinxstylethead`, which by default replaces the font with a Sans Serif font (`\textsf`). Now it replaces it with a bold font.

Note that this won't apply to any tables that don't use the header row (separated by `=========` instead of `----------`), nor will it apply to tables over 30 rows long (like table 3). Large tables will need to be manually bolded.

**Comment by esilvia** [comment]
Upgrading ubuntu versions updated Sphinx and broke the previous fix as expected.
Had to change from...
`\protected\def\sphinxstylethead{\textbf}`
to...
`\protected\def\sphinxstyletheadfamily{\bfseries}`
I'm posting here because it took me a couple hours to figure this out.

**Comment by hobu** [comment]
Thanks for finding this.
