### ISSUE TITLE
Is it valid to have several extrabytes VLR?

### ISSUE THREAD

**Issue by Jean-Romain** [ASPRSorg/LAS#150]
### What is the issue about?

Inquiry about the specification

### Issue description

I recently received a file with three identical VLRs describing three groups of extra-bytes created by three different software applications. To my understanding, this is not compliant with the specifications, and `LASlib` is failing to read the extra-bytes properly.

However, there is fundamentally nothing preventing a reader from supporting this special case. Therefore, I'm wondering whether the software should be enhanced to support this case or if the file should be fixed to be compliant with the specifications.

Does this look like a legitimate file to you? The header has three extra byte definitions for a total of eight extra byte attributes.
 
- RIEGL Extra Bytes
   -  Amplitude
   - Pulse width
   - Reflectance
   - Deviation
- NA 
   - confidence
- TerraScan Extrabytes
   - Distance
   - Group
   - Normal 
 
`lasinfo`

```
variable length header record 2 of 5:
  reserved             0
  user ID              'LASF_Spec'
  record ID            4
  length after header  768
  description          'RIEGL Extra Bytes'
    Extra Byte Descriptions
      data type: 3 (unsigned short), name "Amplitude", description: "Echo signal amplitude [dB]", min:, 0, max:, 10000, scale: 0.01, offset: 0 (not set)
      data type: 3 (unsigned short), name "Pulse width", description: "Full width at half maximum [ns]", min:, 1, max:, 10000, scale: 0.1, offset: 0 (not set)
      data type: 4 (short), name "Reflectance", description: "Echo signal reflectance [dB]", min:, -5000, max:, 15000, scale: 0.01, offset: 0 (not set)
      data type: 3 (unsigned short), name "Deviation", description: "Pulse shape deviation", min:, 0, max:, 65535, scale: 1 (not set), offset: 0 (not set)
variable length header record 3 of 5:
  reserved             0
  user ID              'LASF_Spec'
  record ID            4
  length after header  192
  description          ''
    Extra Byte Descriptions
      data type: 1 (unsigned char), name "confidence", description: "confidence values", scale: 1 (not set), offset: 0 (not set)
variable length header record 4 of 5:
  reserved             0
  user ID              'LASF_Spec'
  record ID            4
  length after header  576
  description          'TerraScan Extra Bytes'
    Extra Byte Descriptions
      data type: 6 (long), name "Distance", description: "Distance", min:, 2147483649, max:, 2147483647, scale: 1, offset: 0 (not set)
      data type: 5 (unsigned long), name "Group", description: "Group", min:, 0, max:, 4294967295, scale: 1, offset: 0 (not set)
      data type: 5 (unsigned long), name "Normal", description: "Normal vector 2+15+15 bits", min:, 0, max:, 0, scale: 1, offset: 0 (not set)
```

**Comment by hobu** [comment]
> three identical VLRs describing three groups of extra-bytes created by three different software applications.

My recollection is Martin and I were thinking a single VLR entry when we developed the extra bytes VLR. Certainly it is valid, but I would argue it was not the expected condition, and software implementations probably do not expect to have to concatenate multiple extra byte VLRs together – I expect they might just take the first one they see and leave the additional bytes uninterpreted.

**Comment by Jean-Romain** [comment]
@hobu Thanks you for your reply.  `LASlib` implementation takes the last definition and thus reads corrupted data. Keeping the first definition would allow, at least, to read the few first extra-bytes properly with minor modification. If this respects the standard I guess concatenation should be supported. But this is no longer a question for ASPRS.

**Comment by manfred-brands** [comment]
@Jean-Romain Can you see if TerraScan actually adds new data or is it overwriting Riegls.

Is the point size matching the sum of all 3 VLRs or only the last.

**Comment by Jean-Romain** [comment]
@manfred-brands good question and I already check it.

It is a LAS 1.4 PDRF 8. The Minimum PDRF Size is 38 bytes.  The point data record length is 59 bytes. According to the header there are 4 `short` + 1 `char` + 3 `long` i.e. an additional payload of 21 bytes for an expected total of 59 bytes. It matches.

**Comment by csevcik01** [comment]
We got the same issue here. 
I agree with @hobu. When reading the standard in context, i tend to lean towards the single VLR intention. Multiple ExtraByte VLRs were not in the mind of the creators. 
Nevertheless LAS files with multiple VLRS with RecordID 4 are around and the major issues we see is the assignemt of the right VLR to the corresponding bytes sequence.
We have come up with no better solution than concatenating all VLRS in the order found in the LAS header and interpret the extra bytes in the PDR accordingly. 
 This feels more of a gentlemen agreement, than a specification to me.

**Comment by abellgithub** [comment]
> Certainly it is valid, but I would argue it was not the expected condition

Is it really valid? Other than those tagged as "superseded", does the specification suggest that duplicates of any VLRs (as keyed by User ID/Record ID) are allowed? This should be clarified.

Assuming that the order of the VLRs matters (which is what this specific EB VLR issue implies), is a problem. There is existing software that moves VLRs around for various reasons when making copies.  This just seems like a rabbit hole best avoided by declaring VLRs with duplicate keys disallowed.

**Comment by hobu** [comment]
> Is it really valid? 

The specification is not clear if it is opt-in or opt-out in regards to these two conditions:

* Anything not specified in the document IS allowed
* Anything not specified in the document IS NOT allowed

Historically, I think it has been implicitly the former, and that's why I said I think it was valid.

> Other than those tagged as "superseded", does the specification suggest that duplicates of any VLRs (as keyed by User ID/Record ID) are allowed? This should be clarified.

Agree. It would be a good LAS 1.5 topic to settle too.

**Comment by esilvia** [comment]
This is a great topic. I agree with @hobu on both the general approach of LAS with respect to silence (silence is permission) and that general understanding is that a VLR Key+RecordID is generally assumed to uniquely refer to a single (E)VLR in a file. The one implied exception is the Superseded VLR, but I don't see anything in the spec that prohibits or prescribes this behavior.

I agree that it would be worthwhile to clarify this point in LAS 1.5 by making it prescriptive. I too have encountered multiple ExtraByte VLRs and seen strange behavior as a result.

**Comment by esilvia** [comment]
[LAS_1.5_with_150.pdf](https://github.com/user-attachments/files/18216724/LAS_1.5_with_150.pdf)
These changes have been incorporated into the most recent LAS 1.5 draft build, attached. Feel free to review and let me know if we missed the mark somehow, and I'll reopen the ticket.
