### ISSUE TITLE
Fix typos in WKT explanation

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#2]
From Martin:

We should also fix these copy and paste errors (and whichever fixes Lewis and others have suggested since rev 13).

OGC COORDINATE SYSTEM WKT:
User ID: LASF_Projection
Record ID: 2112
This record contains the textual data representing a Coordinate System WKT as defined in
section 7 of the Coordinate Transformation Services Spec, with the following notes:
● The OGC Math Transform WKT VLR data shall be a null-terminated string.
● The OGC Math Transform WKT VLR data shall be considered UTF-8.
● The OGC Math Transform WKT VLR data shall be considered C locale-based, and no localization of the numeric strings within the WKT should be performed.

**Comment by HKHeidemann** [comment]
indeed.

**Comment by esilvia** [comment]
Looks like Howard fixed this during his port over to GitHub.
