### ISSUE TITLE
Clean up warnings/errors in TRAVIS-CI build

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#23]
Multiple warnings/errors are present in the TRAVIS build logs:
![image](https://user-images.githubusercontent.com/11743012/29295088-6b22ac72-8107-11e7-82e6-2cdebd4e505d.png)
![image](https://user-images.githubusercontent.com/11743012/29295089-6ecc144e-8107-11e7-8495-1257839c2119.png)

Screenshots from this build: https://travis-ci.org/ASPRSorg/LAS/builds/264392699

**Comment by esilvia** [comment]
`titlesec` bug appears to have been fixed in version 2.10.2: https://tex.stackexchange.com/questions/299969/titlesec-loss-of-section-numbering-with-the-new-update-2016-03-15/300259#300259

I can't figure out where titlesec.sty is packaged, though.

**Comment by esilvia** [comment]
Ah, it's part of the ubuntu Xenial package: https://bugs.launchpad.net/ubuntu/+source/texlive-extra/+bug/1574052/comments/10

**Comment by esilvia** [comment]
@hobu Do you know how to retrieve an updated version of `titlesec.sty`? Is that something we'd do in `travis.yml` or maybe Docker?

**Comment by hobu** [comment]
We can ignore most of the LaTeX warnings. It's an unsatisfactory rabbit hole to follow. If there are more issues like #44, let's open them separately.

**Comment by esilvia** [comment]
+1

**Comment by esilvia** [comment]
Not only that, I've learned that some of the LaTeX warnings are emitted by design, forcing a second pass after table widths (for example) are calculated in the first pass, so fixing them would be fruitless.
