### ISSUE TITLE
"Indices and Tables" section is bugged

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#24]
The last page of the PDF [from index.txt](https://github.com/ASPRSorg/LAS/blob/cca5d288bc7723d5b7fe530ac1e1a58fe3b48824/source/index.txt#L27) looks like it's unresolved code that's supposed to create indices. I'm not sure what it's supposed to do.

**Comment by hobu** [comment]
When I make the next pass through the infrastructure and document stuff, I will make sure to enable upload of the `.tex` file to S3 to ease error discovery.

**Comment by esilvia** [comment]
I managed to upload the TEX file in the latest commit on the master branch. Seems to be working, as far as I can tell.
