### ISSUE TITLE
Reserve class 19 

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#26]
Lewis formally requested that Class 19 be reserved as "Conveyor and overhead mine equipment." Please document objections here.

**Comment by rapidlasso** [comment]
All previous classification names are terse. What is a terse way of
saying "Conveyor
and overhead mine equipment." Also ... we need to get Lewis on GitHub ...
(-:

**Comment by lgraham-geocue** [comment]
Conveyor, overhead eqp?

**Comment by esilvia** [comment]
I like the sound of Overhead Equipment. Conveys the idea that it's not a building and has void space underneath, without limiting itself to mines specifically.

**Comment by csevcik01** [comment]
How does 'Overhead structure' sound to you?

**Comment by esilvia** [comment]
Hm... I don't think I have a strong preference either way. Anyone else?

**Comment by lgraham-geocue** [comment]
Overhead Structure is a bit more generic and hence probably the one to use.

**Comment by rapidlasso** [comment]
Agreed. I like "Overhead Structure" better as well.

**Comment by esilvia** [comment]
Sounds like a consensus. We'll proceed with that barring any objections.
