### ISSUE TITLE
Add OGC endorsement

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#31]
Although the LAS specification is maintained by the ASPRS LWG, it is also endorsed by OGC. Should we explicitly state this in the [Authority](https://github.com/ASPRSorg/LAS/blob/master/source/intro.txt#L46) section? @hobu

**Comment by hobu** [comment]
> Should we explicitly state this in the Authority section?

Yes, I think so. We should also point to supporting documents like the LiDAR Base Specification that have a lot of contextual usage of ASPRS LAS, which would be helpful to implementors trying to write software to support the specification in situations where the text is ambiguous or not detailed enough.

**Comment by esilvia** [comment]
Good idea. Is Karl on here yet? Having his input on language for the LBS would be useful.

**Comment by esilvia** [comment]
@hobu Can you generate a pull request that incorporates this change? I can't figure out how to phrase it.

**Comment by hobu** [comment]
The endorsement was to simply point out that the LBS provides a lot of practical implementation guidance for how to use many of the features in the LAS specification. It is very helpful for a software implementer to see this kind of context to decrease the abstraction level of the specification, especially for some of LAS' more intricate features.

**Comment by rapidlasso** [comment]
I've never used the USGS LBS document for clarifying the LAS specification. Which points does it make more clear?

**Comment by esilvia** [comment]
Here's a PDF of the spec with changes to the Authority section (§1.3): https://s3.amazonaws.com/asprs-las/LAS-specification-768ba771e98a6ffdea1bd36e0c7f1f47179cb7b0.pdf

**Comment by hobu** [comment]
> I remember a pretty nice article written by Lewis about some of the intentions behind the new LAS 1.4 features. Shouldn't that be referenced as well?

Yes. Maybe a separate Resources section or something at the end. We could kick this ahead to R15 too.

**Comment by esilvia** [comment]
@rapidlasso Nice catch. I just fixed that one and another broken link in commit f1cf4b45afb8c1fea957767181f4e9e537c65082 here: https://s3.amazonaws.com/asprs-las/LAS-specification-f1cf4b45afb8c1fea957767181f4e9e537c65082.pdf

I like the idea of a Resources section at the end. I'll split out that part and spin off an issue about that. It could link the Wiki, the PE&RS article by @lgraham-geocue that I currently have printed on my desk but can't find the PDF link, and and USGS LBS.

**Comment by esilvia** [comment]
See #71
