### ISSUE TITLE
Publish as HTML instead of PDF?

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#32]
Right now the LAS Specification is published as a static PDF. However, it could just as easily be published as HTML using the reStructuredText that @hobu implemented for this interface, and might even be the more convenient format for our users. What are the arguments for and against this transition?

**Comment by hobu** [comment]
For historical reasons, I think we want static, versioned snapshots of the specification which lends itself best to PDF-style publication as the primary medium rather than HTML.

That said, as a software implementer, HTML is much easier to link and browse than a PDF.

**Comment by csevcik01** [comment]
I agree with Howard. Personally i'd prefer HTML, but the spec should be officially published as PDF.

**Comment by esilvia** [comment]
That works for me. It's definitely nice to have a printed copy sitting on my desk, and PDF is perfect for that. I'll close the issue.
