### ISSUE TITLE
Missing title page components

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#33]
The original PDF version had the following components that are missing from the title page of the GitHub LaTeX PDF output:

1. Approval date(s)
2. Publication info (ASPRS, address, phone number, fax, webpage)
3. Copyright notice.

I can't figure out how to modify the title page contents to add them back in, so maybe @hobu can? Most of this can probably be moved to a different page, but I think at the very least the approval dates should be on the cover.

New
![image](https://user-images.githubusercontent.com/11743012/30343386-46039372-97b2-11e7-9be7-66578be4287c.png)
Original
![image](https://user-images.githubusercontent.com/11743012/30343496-a6fef4b4-97b2-11e7-9eda-a0042466952e.png)

**Comment by hobu** [comment]
Google `sphinx latex preamble` or something like that and you should be able to find some example of sticking in your own LaTeX preamble.

**Comment by esilvia** [comment]
That's about as far as I got. It looks like it's controlled by the `manual` `documentstyle` that's specified, but I can't find any documentation about that style at all.

http://www.sphinx-doc.org/en/stable/config.html#options-for-latex-output

**Comment by hobu** [comment]
Fixed in #51

**Comment by esilvia** [comment]
Thanks for figuring this out! Would've taken me **hours** (days?) to do this on my own.

**Comment by esilvia** [comment]
Would adding a reference to the GitHub page be a R13 change or R14 change?
![image](https://user-images.githubusercontent.com/11743012/34803694-8109c1d2-f629-11e7-9c67-29fe27a84789.png)

**Comment by hobu** [comment]
13 would seem fine with me
