### ISSUE TITLE
Provide clarification on Endianness and usage of Project GUID fields

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#38]
There's extensive confusion about how to implement the 128-bit GUID in the LAS header, particularly since the [standard method for UUID on wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier) uses five elements (4-2-2-2-6 in bytes) and the LAS header uses four elements (4-2-2-8 in bytes). It's unclear how they should be split, whether UTF-8 characters are encoded vs. numbers, and whether the byte ordering should be Little-Endian (as the rest of the LAS file) or Big-Endian (like the UUID standard).

More detail in the following discussions:

- LAStools discussion: https://groups.google.com/forum/#!topic/lastools/WhrFfvPC90o
- LASroom discussion: https://groups.google.com/forum/#!topic/lasroom/WhrFfvPC90o

**Comment by esilvia** [comment]
Based on the way that it's defined in the LAS header (sequential chars), it looks like the LAS spec most closely aligns with the Microsoft style endian encoding described on the [Wikipedia page](https://en.wikipedia.org/wiki/Universally_unique_identifier#Encoding).

![image](https://user-images.githubusercontent.com/11743012/31466483-2c350fd4-ae8c-11e7-9ba0-ea49b018bd5c.png)

**Comment by esilvia** [comment]
@lgraham-geocue @rapidlasso I can add an example like this to the specification as on page 11 here: https://s3.amazonaws.com/asprs-las/LAS-specification-4753ee7ea9551e3b0b9f1eb257a1c56259c3186f.pdf

Does this work, or does it just complicate the specification? I can also make an explanatory wiki page with some examples instead.

**Comment by lgraham-geocue** [comment]
Are you referring to the use of Offset example?

Lewis Graham
GeoCue Group Inc.
9668 Madison Blvd., Suite 202
Madison, AL 35758 USA
256-461-8289
www.geocue.com<http://www.geocue.com>
Software tools for LIDAR &  Drone Mapping
Bespoke Enterprise Workflow Solutions
Drone Mapping Services
Technical Consulting

**Comment by esilvia** [comment]
No, this is for the old discussion on ProjectID. If it's unclear, you might find it helpful to click on the GitHub link at the bottom of the email to get some context.

**Comment by esilvia** [comment]
Sorry @lgraham-geocue, now I see what you meant. I was referring to Page 11 of the PDF, which is Page 8 of the specification here: https://s3.amazonaws.com/asprs-las/LAS-specification-4753ee7ea9551e3b0b9f1eb257a1c56259c3186f.pdf

I was asking if you'd review the updated language for the `Project ID (GUID Data)` section. Here's a screenshot if that helps:
![image](https://user-images.githubusercontent.com/11743012/47453426-8829e480-d781-11e8-88b1-06e404a6a984.png)

**Comment by esilvia** [comment]
I'm thinking the last sentence could be clarified with brackets like `[33 22 11 00] [55 44] [77 66] [88 99 aa bb cc dd ee ff]` to differentiate between the fields.
