### ISSUE TITLE
Missing section numbering outside the TOC

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#44]
The Table of Contents correctly assigns section numbers:
![image](https://user-images.githubusercontent.com/11743012/34575062-43ebf298-f12e-11e7-9ff1-d3eb25c89dde.png)
But the section & subsection headings themselves don't seem to have the numbers:
![image](https://user-images.githubusercontent.com/11743012/34575119-766bdfd0-f12e-11e7-96ff-e7346d008e79.png)
I've tried a few different iterations of `\setcounter{secnumdepth}` but can't figure out what, exactly, is causing LaTeX to swallow the section numbers. This is what it's supposed to do for HTML output, but as far as I can tell it's supposed to produce these numbers for PDF output.

@hobu Have any ideas?

**Comment by esilvia** [comment]
My attempts to fix this are in the sandbox branch, particularly this commit:
https://github.com/ASPRSorg/LAS/commit/3f6375cf36b041085d7e8eda677ecc4e7b1628cf

**Comment by esilvia** [comment]
I can't help wondering whether it's related to the titlesec.sty issue with #23, which is why I started looking at that in the first place.

**Comment by hobu** [comment]
![screen shot 2018-01-08 at 3 35 07 pm](https://user-images.githubusercontent.com/87751/34693516-8608ac62-f489-11e7-9b7a-bd1fa9d92418.png)

I have updated latexpdf and Sphinx on the Docker container, and I believe we are now getting section numbers.

**Comment by esilvia** [comment]
Updating to Sphinx 1.6.7+ seems to have fixed this issue in the latest builds & commits.
