### ISSUE TITLE
Clarify (E)VLR descriptions don't have to be null-terminated

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#46]
Because the (E)VLR description field is a fixed length, the `char` array doesn't have to be null-terminated like the spec claims, if all 32 characters are used in the description. All the readers I've tested support this functionality.

Don't forget to update both the VLR **and** EVLR descriptions.

**Comment by rapidlasso** [comment]
Is that really so? Not the case for lasinfo of LAStools (and who knows how many other software packages) that may assume a null-terminated string:

```
for (int i = 0; i < (int)lasheader->number_of_variable_length_records; i++)
{
  fprintf(file_out, "variable length header record %d of %d:\012", i+1, (int)lasheader->number_of_variable_length_records);
  fprintf(file_out, "  reserved             %d\012", lasreader->header.vlrs[i].reserved);
  fprintf(file_out, "  user ID              '%s'\012", lasreader->header.vlrs[i].user_id);
  fprintf(file_out, "  record ID            %d\012", lasreader->header.vlrs[i].record_id);
  fprintf(file_out, "  length after header  %d\012", lasreader->header.vlrs[i].record_length_after_header);
  fprintf(file_out, "  description          '%s'\012", lasreader->header.vlrs[i].description);
}
```

**Comment by esilvia** [comment]
lasinfo doesn't appear to have any trouble with it...
[tiny.zip](https://github.com/ASPRSorg/LAS/files/1613313/tiny.zip)

**Comment by esilvia** [comment]
Forgot the screenshot:
![image](https://user-images.githubusercontent.com/11743012/34696088-4d5bd616-f482-11e7-879b-78c07330a2ae.png)

**Comment by rapidlasso** [comment]
It is not guaranteed to work as the fprintf() statements in the code excerpt should tell you. I assume that the byte following your "12345678901234567890123456789012" string happens to be a zero byte. That should be the highest byte of the raw X integer coordinate of the first return. What is your motivation for loosening that part of the specification? Some implementation may rely on it. I don't think it is good practice for a specification to change in a way that introduces potential risk for those assuming content to conform to the current specification. It has always stated that the string should be null-terminated and I have therefore always set the last byte of the description[31] to '\0' when creating a VLR/EVLR.

**Comment by esilvia** [comment]
My implementation used all 32 bytes because every character counts. 32 characters is pretty darn short for a description so I wanted to avoid wasting a character on null-terminating, which is unnecessary for a fixed-length char array.

But what you say makes sense. I guess the cat's out of the bag on this one. I'll close the issue.

**Comment by esilvia** [comment]
@rapidlasso Hmm... Your implementation seems to also assume that the User ID is null-terminated, which is not required by the specification. In fact, the specification seems to imply that all 16 characters are available for use. Seems to me that one of these issues needs to be clarified.

Of course, since UserIDs are supposedly [managed by the LWG](http://www.asprs.org/misc/las-key-list.html) it shouldn't ever be an issue, but it might and at least two of the UserIDs I inherited are too long by this definition.

**Comment by esilvia** [comment]
The same is true for the `name` and `description` fields of the `ExtraByte` VLR contents. No mention of a requirement for null termination.

@hobu How did you implement this?

**Comment by hobu** [comment]
> @hobu How did you implement this?

libLAS and PDAL allow all of the bytes and are not NULL-terminated because it was given a fixed size.

**Comment by rapidlasso** [comment]
Would be trivial to fix in my tools (and allow use of all 32 bytes) but I'll probably continue to set the last byte to zero wherever I produce those strings in my libs and DLLs just because (a) the lack of the last byte of storage space has apparently not been an issue in the last 10 years for users of LASlib of LASzip interfaces and hence (b) why take the risk of breaking something.

**Comment by esilvia** [comment]
this is just a demo comment for the ILMf conference @hobu @jstoker74  You know, it might be related to issue #10
