### ISSUE TITLE
"Correct" Vertical CS codes for NAVD88 and NGVD29?

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#58]
It came to my attention that there's some conflict between the geotiff specification (http://geotiff.maptools.org/spec/geotiff6.html#6.3.4)...
![image](https://user-images.githubusercontent.com/11743012/39453827-a6a02d96-4c8c-11e8-9921-9357ec087d5c.png)
...and the EPSG registry (http://epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::5703)...
![image](https://user-images.githubusercontent.com/11743012/39453870-e84fd796-4c8c-11e8-8ff9-3f40e8aefea8.png)
...on the correct way to define heights for the LAS 1.2 geotiff style of vertical coordinate systems.

Is one of those more correct than the other? Or are both equally correct?

On the one hand, the LAS spec states throughout that it's intended to follow the Geotiff specification without mentioning EPSG explicitly, but on the other hand the Geotiff specification doesn't list all possible coordinate systems and so it's been generally understood to imply that EPSG codes should be supplemented for missing CRS definitions.

See this LAStools conversation for some context: https://groups.google.com/d/msg/lastools/9fUZaLKPReg/1ekK6mNCAwAJ

**Comment by forkozi** [comment]
First...awesome work with this GitHub-LAS-specs initiative.  Second...I'm a little lost with defining the vertical coordinate system in las files.   A quick pdf search of the 1.4 spec reveals 2 instances of the word "vertical."  Do the specs require the vertical CS be defined?  If so, is the vertical CS supposed to be part of a "compound CS," or a separate vertical-only CS contained in a different VLR?  Thanks!

**Comment by hobu** [comment]
> Do the specs require the vertical CS be defined?

The LAS specification does not require it, but follow-on documents like the [LiDAR Base Specification](https://pubs.er.usgs.gov/publication/tm11B4) do

> If so, is the vertical CS supposed to be part of a "compound CS," or a separate vertical-only CS contained in a different VLR?

Part of the compound CS.

**Comment by kjwaters** [comment]
I think you'll find that you're looking at the datum versus the coordinate system. For instance, NAVD88 (meters) is code 5103 if you're talking about the vertical datum and 5703 if you're talking about the coordinate system. Both are EPSG codes. So, 5703 should go with tag 4096 (VerticalCSTypeGeoKey) and 5103 would go with tag 4098 (VerticalDatumGeoKey). Yes, the table in geotiff does label the datum code as a CS.

**Comment by esilvia** [comment]
@kjwaters Ahhh, thank you Kirk!! I knew it had to be something like that but I couldn't reconcile what I was seeing.

@hobu You're exactly right. I'm hoping that LAS 1.5 can make this more explicit with WKT2.

@forkozi Glad it's working for you!
