### ISSUE TITLE
Clarify some fields inside the "Classification" standard

### ISSUE THREAD

**Issue by appanacca** [ASPRSorg/LAS#74]
Hello, I am currently working on a classification problem on some lidar data. I think that the standard for the different classes inside "Classification" poses some ambiguities.

Is it possible to add some extra content to better define for example the vegetation classes (3, 4, 5) ?
Also the difference between low and high noise (classes 7 and 18) is not clear to me.

Thank you

**Comment by esilvia** [comment]
Hello there! Great questions.

Regarding the vegetation classes (3-5), I think they're intentionally ambiguous. I've seen a pretty wide range of the height thresholds to differentiate between these classes, as it varies between vegetation types, application, etc etc. Usually it's determined based on a certain height from ground, but that's not a requirement and I don't think it makes sense to restrict it in the specification. I feel like this came up in a LAStools discussion thread somewhat recently... I couldn't find it, but maybe @rapidlasso can?

For class 7 vs class 18, the distinction is basically whether the noise points are below (class 7) or above (class 18) the surface of interest, which is usually the ground surface. Noise isn't rigidly defined, but it's generally acknowledged to be an erroneous return that doesn't correspond to a real object, or an object that wasn't intended to be part of the dataset (e.g., a large bird or smoke plume).

Does that help?

**Comment by appanacca** [comment]
Thank you for the answer, now it is clear.
