### ISSUE TITLE
Misc editorial wording corrections to include in R15

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#78]
A collection of editorial changes compiled from offline communication with @milenajaniec based on R14:

1. In five instances (on pages 11, 14, 18, and 28) we could insert a comma after "thus."
2. On page 16, perhaps we could replace "LAS file I/O software" with "LAS file Input/Output (I/O) software"?
3. On page 20 (within footnote 10), we could omit a specific example of TerraScan, and simply state "We are using both 0 and 1 as Unclassified to maintain compatibility with current classification software."
4. In few instances (on pages 10, 12,13) reverse "then, if" sentence structure to "if, then"... For example:
    - Before: "It should not be set if the file writer wishes to ensure legacy compatibility (which means the CRS must be GeoTIFF)."
    - After: "If the file writer wishes to ensure legacy compatibility (which means the CRS must be GeoTIFF), then it should not be set."
5. On pages 19, 29,44, after "If set", we could insert a comma as well.

**Comment by mstucky-mc** [comment]
I believe there is an error on Page 27 in the Note below Table 15.  wording should be "The following six fields (Return Number, Number of Returns, Classification Flags, Scanner Channel, Scan Direction Flag, and Edge of Flight Line) are bit fields, encoded into two bytes."

**Comment by esilvia** [comment]
Changes made for @milenajaniec:
1. Added three commas and changed two instances of "thus' to "therefore".
2. I changed "LAS file I/O software" to just "Software".
3. No change. Personally, I don't have an issue with calling out TerraScan in particular if that helps readers correctly understand the context.
4. I opted not to do this change when I felt doing so would break the pattern of the field definitions. 
    * Page 10: no change. 
    * Page 11: Reversed order in description of **Offset to Point Data** to read "If any software add/removes data to/from the Variable Length Records, then this offset value must be updated."
    * Page 12: Reversed order in description of  **Number of Variable Length Records** to read "If the number of VLRs changes, then this number must be updated."
    * Page 13: Reversed order in description of **Number of Extended Variable Length Records** to read "If the number of EVLRs changes, then this number must be updated." Also added a similar phrase to **Start of First Extended Variable Length Record** to reflect the pattern started in **Offset to Point Data**.
5. Homogenized punctuation and usage of "If set" phrase for bit fields descriptions in Tables 8, 16, and 25.

**Comment by esilvia** [comment]
@mstucky-mc I've moved your comment to #80. Nice catch! That's an old typo.
