### ISSUE TITLE
Max/Min Values in Header

### ISSUE THREAD

**Issue by JeffreyWalker** [ASPRSorg/LAS#79]
LAS Specification 1.4 R14 has reordered the MAX/MIN XYZs in the Header.   Previous releases were MAX X, MIN X, ... MAX Z, MIN Z.   New spec is reordered to MAX X, Y, Z, MIN X, Y, Z.

**Comment by hobu** [comment]
I do not think this was intentional. @esilvia ?

**Comment by rapidlasso** [comment]
Probably a little error that no one caught. Who checks for that, especially when the order seem quite logical. It's probably the one that I would have chosen had I been part of the [LAS design committee at its inception in 2004](https://www.conftool.com/gsw2019/sessions.php) ... (-:

**Comment by JeffreyWalker** [comment]
No especially since R13 is the old way

**Comment by rapidlasso** [comment]
Wow! So you may have the early (and lost) history of the LAS format in your email archive ... ?

**Comment by JeffreyWalker** [comment]
Could be.. What you looking for? You were around for the 2.0 proposal.

**Comment by rapidlasso** [comment]
Yes. That was exactly the time when I got involved with LAS ([to complain big time](https://groups.google.com/d/topic/lastools/PDvFLk_Rzz0/discussion)).

**Comment by esilvia** [comment]
Dang. That most definitely was not intentional. Thanks @JeffreyWalker 

Hm... is this something we correct in an errata of R14, or do we immediately publish R15 as a correction to R14? Thoughts?
