### ISSUE TITLE
Clarification of GPS time stamps

### ISSUE THREAD

**Issue by rapidlasso** [ASPRSorg/LAS#81]
The current wording states that "the GPS time is the double floating point time tag value at which the point was acquired" and some folks seem to think that this means that different points will get different GPS times depending on what time the pulse was fired plus the round trip distance of the registered photon peak that corresponds to the return. It really should state that "the GPS time is a unique double floating point time tag value corresponding to the GPS time at which the laser pulse was fired that acquired all (up to 15 for PRDF 6 or higher and up to 7 for for PRDF 5 or lower) discrete returns. It is a mechanism that allows to group together all discrete returns of the same laser pulse (with the same scanner channel for PRDF 6 or higher)."

**Comment by esilvia** [comment]
Thanks for submitting this Martin. I think this is definitely worth clarifying. All of the data I've seen has appeared to interpret the timestamp as the time at which the pulse was emitted, but I wasn't sure whether we should assert that interpretation in the specification.

Is there any other valid interpretation, or is this what was originally intended?

**Comment by rapidlasso** [comment]
This is the only mechanism we have to group the returns of the same laser shot together. And it's also the moment in time that counts in terms of relating the return to the trajectory. The moment in time and the orientation and position of the laser origin when the photons that make up this return were released.

**Comment by esilvia** [comment]
How about this phrasing?

```
The GPS Time is the double floating point time tag value at which the point was observed. It is GPS Week Time if the Global Encoding low bit is clear and Adjusted Standard GPS Time if the bit is set.

It is intended that all returns for a given pulse would have an identical GPS Time. Thus, for time-of-flight systems, the GPS Time should be the time at which the pulse was emitted. For :ref:`Aggregate Model Systems <aggregate_link>`, the GPS Time should be set to zero unless assigned from a component measurement.
```

**Comment by esilvia** [comment]
Or perhaps this?

```
The GPS Time is the double floating point time tag value at which the point was
observed. It is GPS Week Time if the Global Encoding
low bit is clear and Adjusted Standard GPS Time if the bit is set.

It is intended that all returns for a given pulse would have an identical GPS
Time. For example, for time-of-flight systems the GPS Time should be the time at
which the pulse was emitted (which is identical for all returns) and not the
time at which the pulse was recorded (which is different for each return).

For Aggregate Model Systems, the GPS Time should be set
to zero unless assigned from a component measurement.
```

**Comment by esilvia** [comment]
One last interation. I think I like this best @rapidlasso 

```
The GPS Time is the double floating point time tag value at which the point was
observed. It is GPS Week Time if the Global Encoding
low bit is clear and Adjusted Standard GPS Time if the bit is set.

It is intended that each return of a given pulse would have an identical GPS
Time. In the example of pulsed LiDAR systems, the GPS Time would be the time at
which the originating pulse was emitted, not the time at which each return was
recorded.

For Aggregate Model Systems, the GPS Time should be set
to zero unless assigned from a component measurement.
```

I didn't include your comment about grouping returns or mention channels, but it didn't seem necessary to me. Does this work for you?

**Comment by manfred-brands** [comment]
The word "observed" isn't clear or contradicts with your later explanation where you specify it to be the time of transmit instead of the time of receive. Note, that I agree with that explanation.
Without that paragraph observed sound like "when seen aka received".
Could you change "was observed" into something else such as "originated"? Or something better.

**Comment by esilvia** [comment]
Good point. Once more into the breach, dear friends!

```
The GPS Time is the double floating-point time value at which the point 
originated. It is GPS Week Time if the Global Encoding
low bit is clear and Adjusted Standard GPS Time if the bit is set.

It is intended that each return of a given pulse would have an identical GPS
Time. In the example of pulsed LiDAR systems, the GPS Time would be the time at
which the originating pulse was emitted, not the time at which each return was
recorded.

For Aggregate Model Systems, the GPS Time should be set
to zero unless assigned from a component measurement.
```

**Comment by esilvia** [comment]
General agreement with current wording on today's bimonthly LWG call. Queued for R16 draft and closed.
