### ISSUE TITLE
Reword mandatory zero classification for synthetic LiDAR

### ISSUE THREAD

**Issue by pchilds** [ASPRSorg/LAS#86]
The specification for classification states:
> This field represents the “class” attributes of a point. If a point has never been classified, this byte
must be set to zero

As it stands this states that the synthetic, key-point and withheld flags would also be zeroed. I believe this should say "the lowest five bits must be set to zero" as a point never being classified should not preclude it being synthetically derived.

**Comment by esilvia** [comment]
That makes sense to me. I'll queue this for the next update.

**Comment by esilvia** [comment]
@pchilds The requested edit is available in this PDF:
https://github.com/ASPRSorg/LAS/suites/1771901034/artifacts/33823782
Can you please review?

**Comment by pchilds** [comment]
Can't view the pdf via the link, but the commit looks good

**Comment by esilvia** [comment]
@pchilds Glad it looks good. Here's the actual PDF, attached.
[LAS.pdf](https://github.com/ASPRSorg/LAS/files/6053302/LAS.pdf)

I'm going to close this as complete. Feel free to reopen if you see an issue.
