### ISSUE TITLE
Improve wording for FWF encoding

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#9]
Martin produced some helpful graphics for explaining the expectations for full waveform (FWF) data encoding. He has worked with the major sensor manufacturers on adopting these conventions, so it would be helpful to reflect that in the specification itself.

Relevant discussion here:
https://groups.google.com/forum/#!msg/lasroom/g4VsXH3CRZo/pMn_JFQD0kwJ;context-place=msg/lasroom/s3-OR4LP1IE/Br-PndbgCwAJ

**Comment by esilvia** [comment]
The first version of the wiki page has been released! https://github.com/ASPRSorg/LAS/wiki/Waveform-Data-Packet-Descriptors-Explained

Please provide comments and revisions here. This wiki reflects some wording changes that will be included in the R14 release.

**Comment by esilvia** [comment]
Bump. Haven't seen any comments on this. Any thoughts? @rapidlasso @hobu @lgraham-geocue 

As the first wiki on here, I'm also soliciting comments on that concept.

**Comment by rapidlasso** [comment]
Not sure what else to add but each time a new exporter is written people seem to [struggle again](https://groups.google.com/d/topic/lastools/TxaPA-WRSPQ/discussion) with writing correct LAS FWF files (also the case for PulseWaves but maybe for different reasons).

**Comment by esilvia** [comment]
Totally agree. I'm hoping that as this page gets more exposure we'll be able to find out where the sticking points are. I'm hoping our friends at Riegl can take this for a test drive and let us know where it's deficient. Maybe @csevcik01 can help?

**Comment by esilvia** [comment]
Hopefully people have had ample time to review this and silence means approval. I'm going to implement as discussed, link to the wiki page from R14, and move on.

**Comment by rapidlasso** [comment]
I have totally fallen out of love with the LAS FWF extension. I keep on seeing poopy data like this recent example.

https://groups.google.com/d/msg/lastools/q85T9JWiw68/6C7VMEYZBAAJ

**Comment by esilvia** [comment]
Yeah, I had the same suspicion that you did when I saw that post. Curiously, FWF as encoded in LAS has the same units/CRS limitation that we've been discussing for ExtraBytes in #37.

I can't help thinking that its shortcomings are part of the reason it's underutilized, although I'd posit that being flawed doesn't make it useless, which is why the wiki might be helpful.
