### ISSUE TITLE
Validity of extra bytes at end of header

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#91]
Is it valid for LAS files to insert bytes between the end of the last VLR and the beginning of the point data records? LAS 1.4 R15 reads thus:
![image](https://user-images.githubusercontent.com/11743012/80152326-4e9d8980-8570-11ea-8f5c-baad46ac0367.png)
Although it explicitly says not to extend the header record, it doesn't mandate that `Offset to Point Data = Header Size + sum(VLR Size)`. It shouldn't affect a high quality LAS reader, but I can see it impacting poorly written readers that mistakenly expect the point records to begin immediately after streaming the last VLR, rather than relying on the `Offset to Point Data`.

I know of at least two software companies that leverage this ambiguity to inject non-VLR information into the header. I'm sure there's others and I'm not calling them out as making a mistake... they're just examples.

TerraScan has a long history of appending exactly two bytes to the end of the LAS header, after the VLRs but before the point data begins, presumably because the original LAS 1.0 header had a marker at the start of the point data record. 

GeoCue also inserts additional bytes between the end of the last VLR and the start of the first point record, between a couple hundred bytes and tens of thousands of bytes. I haven't taken the time to dig deeper, but the samples I've seen don't appear to be undocumented VLRs.

So is this valid or no?

**Comment by esilvia** [comment]
To be clear, in the examples I've seen the LAS header size is still the standard value as required... it's just that there are undocumented bytes when the `Offset to Point Data` is greater than you'd expect from adding up the header size plus all of the VLRs.

**Comment by rapidlasso** [comment]
Yes  This is valid. @lgraham-geocue has done that for years as far as I know. Always allocatio 1024 or 2048 bytes fot the header so you can rewrite existing VLRs and/or add missing VLRs in place without a complete rewrite.

**Comment by dpev** [comment]
This is a good idea, but it would be better for the committee to define a
standard 'padding' VLR for that purpose.

**Comment by abellgithub** [comment]
If you feel the need to say that point data can start at any position after the VLRs, so be it, but the train has already left the station, so you're just clarifying what's already done in practice, and I think supported by all readers.

**Comment by rapidlasso** [comment]
You go and tell @lgraham-geocue that all the LAS files his software has expored over the past 10 year is no longer specification conform. I had one laser war with Lewis. I do not want another one. My next laser war will be a cause more worthy then a small LiDAR point cloud format detail. That was just for practice. But I have not yet decided. Either the corupt military-industrial complex, the abusive for-profit jail system, the destructive monoculture practices, or all three. (-;

**Comment by manfred-brands** [comment]
The Offset to Point data field allows skipping VLRs if one is only interested in core information. If we only would accept directly joining points that would make that field void. So yes, I also think it is valid.

**Comment by dpev** [comment]
I'm not disputing the validity. Currently, geocue uses the feature quite
nicely to add/remove vlrs without a rewrite. Several other softwares could
do the same, or maybe they put something else there, but they can't
interoperate because they don't know what the data in that gap is. A
standard vlr for this purpose means more interoperability, and coupled with
a recommended pad size las files produced with the vlr can be modified by
all software.

**Comment by esilvia** [comment]
> I'm not disputing the validity. Currently, geocue uses the feature quite nicely to add/remove vlrs without a rewrite. Several other softwares could do the same, or maybe they put something else there, but they can't interoperate because they don't know what the data in that gap is. A standard vlr for this purpose means more interoperability, and coupled with a recommended pad size las files produced with the vlr can be modified by all software.

LAS 1.4 added the Superceded VLR, which is meant to allow the "deletion" of a VLR in-place without rewriting the entire file. I suppose it could also be used as a padding VLR if one wanted to "insert" a VLR after the fact.

Nevertheless, I'm inclined to instead endorse the current practice by adding this "padding" between the VLRs and point data in Table 1 of section 2 and modifying the description of Offset to Point Data to account for the potential of this "junk" padding. Or would that be too confusing and I should just leave well enough alone?

**Comment by rapidlasso** [comment]
Why is the USGS defaming, slandering and abusing me? These are totally false allegations!!!
![HIGH_PRIORITY_LASTool_Suite_Presents_Potential_Risk_to_USGS_Projects_and_Programs](https://user-images.githubusercontent.com/1107656/104673104-58a87f00-56e1-11eb-99ee-e3dcf80cc31b.png)
