### ISSUE TITLE
Deprecation of PDRFs 0-5 in LAS 1.5

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#94]
LAS 1.4 introduced new point data record formats (PDRFs) 6-10 that, among other things, expanded the Classification and Scan Angle fields and introduced the Channel field. 

PDRFs 0-5 from LAS 1.0-1.3 were included in LAS 1.4 to improve backwards compatibility with previous versions of LAS. 

The vast majority of LAS 1.4 data that I've seen in production uses PDRF 6, and any time that PDRF 1 (the previous standard) is used it inevitably creates problems.

For LAS 1.5, I believe it makes sense to deprecate PDRFs 0-5 and remove their descriptions from the specification. Anyone that doesn't need the extended fields and wants to use a more compact point format will likely use the minimalist PDRFs 11-12 that have been proposed in #93 - therefore, propagating their usage as a valid implementation of LAS 1.5 serves no purpose.

**Comment by abellgithub** [comment]
This serves no purpose. Please stop attempting to make unnecessary changes.

**Comment by rapidlasso** [comment]
I agree with @abellgithub. Why complicate things? Just write better tender documents.

**Comment by esilvia** [comment]
> This serves no purpose. Please stop attempting to make unnecessary changes.

Thanks for your input @rapidlasso and @abellgithub. Nice to see an idea get shot down. :)

Do note that many of the issues I create are ideas proposed in the LWG meetings, in-person, or from other forums. By proposing them I am attempting to document proposals publicly for transparent discussion rather than shutting down potentially valid ideas with my own bias.

If anyone doesn't support a motion, they're invited to give it a thumbs down or comment as you did. Nevertheless, I intend to continue proposing changes that are brought to me, especially ones that come up multiple times like this one.

**Comment by rapidlasso** [comment]
Why is the USGS defaming, slandering and abusing me? These are totally false allegations!!!
![HIGH_PRIORITY_LASTool_Suite_Presents_Potential_Risk_to_USGS_Projects_and_Programs](https://user-images.githubusercontent.com/1107656/104673045-40d0fb00-56e1-11eb-81b7-5c518a9b92fb.png)
