### ISSUE TITLE
LAS CRS usage in non-mapping/purely-local applications

### ISSUE THREAD

**Issue by esilvia** [ASPRSorg/LAS#98]
I recently heard that JPEG is working on publishing yet another ISO point cloud format: http://ds.jpeg.org/documents/jpegpleno/wg1n86012-REQ-JPEG_Pleno_Point_Cloud_Use_Cases_and_Requirements_v1_3.pdf

This made me realize (again) that LAS is tuned for remote sensing _mapping_ applications, and that's not more obvious than in the CRS requirement for a "valid" LAS file. This requirement as commonly understood doesn't make sense for point clouds at the handheld scale (e.g., 3D printing, facial scans, localized TLS scans) and it's unclear how one might "properly" encode the CRS for such "purely-local" applications and still be valid.

Is there a canonical way to encode WKT with a purely-local CRS (referenced to 1000,1000 or even the scanner itself), or do we need to add one?

(Thanks to to @mjolsen for bringing this to my attention)

**Comment by esilvia** [comment]
I should add that my understanding is that those needing purely local CRS definitions generally omit the CRS VLRs altogether, which of course produces a technically invalid LAS.

**Comment by kjwaters** [comment]
Evon,
I didn't dig very far into this, but I think there may be a way. I believe
an engineering CRS is what you're looking for.
http://docs.opengeospatial.org/is/18-010r7/18-010r7.html#60

Kirk

**Comment by vminor** [comment]
Evon and Kirk,

It might be better to look at the CRS definition (the CS is basically just
the Axis description).

http://docs.opengeospatial.org/is/18-010r7/18-010r7.html#92

Using that, this is what an "Engineering CRS" might look like for a given
sensor:

ENGCRS["A Specific Sensor CRS",
  EDATUM["Wand center location",
        ANCHOR["Center of System : Right Corner marker Prince Albert
Hall"]],
  CS[Cartesian,3],
  AXIS["(x)",X],
  AXIS["(y)",Y],
  AXIS["(z)",Z],
  LENGTHUNIT["meter",1.0]
]

One note, the Engineering system exists in the WKT version 2 specification
(ISO 19162:2019) but it's probably not going to be recognized by many
software packages on the market that read WKT (it ain't 'GIS').
Additionally, it is probably important that the Datum be something unique
for each survey, unless all of the constraints and parameters match a
previous collection. If the above definition was used in every custom local
survey the implication is that all of the data is in the same coordinate
space, which would not necessarily be true.

Victor

**Comment by rapidlasso** [comment]
Why is the USGS defaming, slandering and abusing me? These are totally false allegations!!!
![HIGH_PRIORITY_LASTool_Suite_Presents_Potential_Risk_to_USGS_Projects_and_Programs](https://user-images.githubusercontent.com/1107656/104673030-34e53900-56e1-11eb-803c-85e30460c364.png)

**Comment by esilvia** [comment]
@vminor Not sure how I missed this post. Thanks for the contribution that directly answers my question!
